//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentRegistration
    {
        public long AgentRegistrationId { get; set; }
        public long UserId { get; set; }
        public string AgentId { get; set; }
        public long ProofTypeId { get; set; }
        public string ProofIDNumber { get; set; }
        public Nullable<int> NumberoRefferal { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ProofType ProofType { get; set; }
    }
}
