//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Collections.Generic;

    public partial class AppUser
    {
        public AppUser()
        {
            this.AgentRegistrations = new HashSet<AgentRegistration>();
            this.AppUserLogs = new HashSet<AppUserLog>();
            this.Referrals = new HashSet<Referral>();

            this.Transactions = new HashSet<Transaction>();
            this.TransactionDetails = new HashSet<TransactionDetail>();

            this.UserSubjects = new HashSet<UserSubject>();
        }

        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long MobileNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public Nullable<long> AgentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }

        public virtual ICollection<AgentRegistration> AgentRegistrations { get; set; }
        public virtual ICollection<AppUserLog> AppUserLogs { get; set; }
        public virtual ICollection<Referral> Referrals { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }

        public virtual ICollection<UserSubject> UserSubjects { get; set; }
    }
}
