//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserLog
    {
        public long UserLogId { get; set; }
        public long UserId { get; set; }
        public System.DateTime LastLogInDatetime { get; set; }
        public Nullable<System.DateTime> LastLogoutDatetime { get; set; }
        public string UserAgent { get; set; }
        public string UserLoggedInIP { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
