//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class developmentEarthEntities : DbContext
    {
        public developmentEarthEntities()
            : base("name=developmentEarthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgentRegistration> AgentRegistrations { get; set; }
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<AppUserLog> AppUserLogs { get; set; }
        public DbSet<ProofType> ProofTypes { get; set; }
        public DbSet<Referral> Referrals { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<TransactionDetail> TransactionDetails { get; set; }
        public DbSet<TransactionType> TransactionTypes { get; set; }
        public DbSet<UserSubject> UserSubjects { get; set; }
    }
}
