//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProofType
    {
        public ProofType()
        {
            this.AgentRegistrations = new HashSet<AgentRegistration>();
        }
    
        public long ProofTypeId { get; set; }
        public string ProofType1 { get; set; }
    
        public virtual ICollection<AgentRegistration> AgentRegistrations { get; set; }
    }
}
