//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public long TransactionTypeId { get; set; }
        public string TransaactionType { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
