//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentEarth.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Transactionid { get; set; }
        public long UserId { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public bool Isactive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
